mod button;
mod core;
mod hyperlink;
pub mod layout;
mod placeholder;
mod text;
mod text_input;

pub use self::core::WidgetCore;
use crate::stroke::Stroke;
use crate::widget_manager::WidgetBox;
use crate::{Event, Font, HorizontalAlignment, Rect, SizeConstraints, VerticalAlignment};
pub use button::Button;
use druid_shell::kurbo::{Point, Size};
use druid_shell::piet;
use druid_shell::Region;
pub use hyperlink::Hyperlink;
use piet::PaintBrush;
pub use placeholder::Placeholder;
use std::any::Any;
use std::cell::RefCell;
use std::fmt::{Debug, Formatter};
pub use text::Text;
pub use text_input::TextInput;

///
pub type WidgetId = usize;

///
#[derive(Debug)]
pub enum WidgetError {
    NoSuchWidget(WidgetId),
    NotHandled,
}

// =================================================================================================

/// An event generated by a widget.
#[derive(Debug)]
pub enum WidgetEvent {
    /// The widget was clicked.
    Clicked(WidgetId),
    /// The widget gained focus.
    GainedFocus(WidgetId),
    /// The widget lost focus.
    LostFocus(WidgetId),
    /// The widget was submitted, e.g. by pressing Enter on a text input.
    Submitted(WidgetId),
    /// The widget's value was changed.
    ValueChanged(WidgetId, Box<dyn Any>),
}

// =================================================================================================

///
#[derive(Clone, Debug)]
pub enum WidgetsLocation {
    Column(usize),
    LastColumn,
    LastRow,
    Row(usize),
}

// =================================================================================================

///
#[derive(Clone, Debug)]
pub enum WidgetPlacement {
    Above(WidgetsLocation),
    Below(WidgetsLocation),
    LeftOf(WidgetsLocation),
    RightOf(WidgetsLocation),
}

// =================================================================================================

/// The widget trait
///
/// A widget should try to be as small as possible.
pub trait Widget {
    ///
    fn add_child(
        &mut self,
        _widget_placement: Option<WidgetPlacement>,
        _child_widget: WidgetBox,
    ) -> Result<(), WidgetError> {
        Err(WidgetError::NotHandled)
    }

    ///
    fn apply_size_constraints(&mut self, size_constraints: SizeConstraints) -> Size;

    /// Returns the widget's flex factor.
    fn flex_factor(&self) -> u16 {
        0
    }

    /// Let the widget handle the given event.
    fn handle_event(&mut self, event: &Event, widget_events: &mut Vec<WidgetEvent>);

    /// Paints the widget.
    fn paint(&self, piet: &mut piet::Piet, region: &Region) -> Result<(), piet::Error>;

    ///
    fn rectangle(&self) -> &Rect;

    /// Removes the widget's child with the given ID.
    fn remove_child(&mut self, _widget_id: WidgetId) -> Result<(), WidgetError> {
        Err(WidgetError::NotHandled)
    }

    /// Removes all of the widget's child widgets.
    fn remove_children(&mut self) -> Result<(), WidgetError> {
        Err(WidgetError::NotHandled)
    }

    /// Returns the widget's selected value.
    fn selected_value(&self) -> Option<Box<dyn Any>> {
        None
    }

    ///
    fn set_child(
        &mut self,
        _column_index: usize,
        _row_index: usize,
        _child_widget: WidgetBox,
    ) -> Result<(), WidgetError> {
        Err(WidgetError::NotHandled)
    }

    ///
    fn set_debug_rendering(&mut self, debug_rendering: bool);

    /// Sets the widget's fill.
    fn set_fill(&mut self, _fill: Option<PaintBrush>) -> Result<(), WidgetError> {
        Err(WidgetError::NotHandled)
    }

    /// Sets the widget's font.
    fn set_font(&mut self, _font: Font) -> Result<(), WidgetError> {
        Err(WidgetError::NotHandled)
    }

    ///
    fn set_has_focus(&mut self, _has_focus: bool) -> Result<(), WidgetError> {
        Err(WidgetError::NotHandled)
    }

    /// Sets the widget's horizontal alignment.
    fn set_horizontal_alignment(
        &mut self,
        _horizontal_alignment: HorizontalAlignment,
    ) -> Result<(), WidgetError> {
        Err(WidgetError::NotHandled)
    }

    ///
    fn set_is_disabled(&mut self, is_disabled: bool);

    ///
    fn set_is_hidden(&mut self, is_hidden: bool);

    ///
    fn set_value(&mut self, _value: Box<dyn Any>) -> Result<(), WidgetError> {
        Err(WidgetError::NotHandled)
    }

    /// Sets the widget's origin.
    fn set_origin(&mut self, origin: Point);

    /// Sets the widget's stroke.
    fn set_stroke(&mut self, _stroke: Option<Stroke>) -> Result<(), WidgetError> {
        Err(WidgetError::NotHandled)
    }

    /// Sets the widget's vertical alignment.
    fn set_vertical_alignment(
        &mut self,
        _vertical_alignment: VerticalAlignment,
    ) -> Result<(), WidgetError> {
        Err(WidgetError::NotHandled)
    }

    /// Returns the widget's ID.
    fn widget_id(&self) -> &WidgetId;
}
