/// The type of an event generated by a widget.
#[derive(Clone, Debug, Eq, Hash, PartialEq)]
pub enum WidgetEventType {
    /// The widget was clicked.
    Clicked,
    /// The widget gained focus.
    GainedFocus,
    /// The widget lost focus.
    LostFocus,
    /// The widget was submitted, e.g. by pressing Enter on a text input.
    Submitted,
    /// The widget's value was changed.
    ValueChanged,
}
